package generate

import (
	"go/ast"
)

// this file is autogenerated.
// run `go generate` to update it.

// WithDoc attaches documentation to this FieldGroup.
func (b *FieldGroupBuilder) WithDoc(lines ...string) *FieldGroupBuilder {
	if len(lines) > 0 {
		b.field.Doc = createDocComment(lines)
	}
	return b
}


func (b *InterfaceDefinitionBuilder) RenderExpr() ast.Expr {
	return b.iface
}


func (b *StructDefinitionBuilder) RenderExpr() ast.Expr {
	return b.strct
}


func (b *FieldGroupBuilder) RenderField() *ast.Field {
	return b.field
}


func (b *FunctionDefinitionBuilder) RenderFuncType() *ast.FuncType {
	return b.fun
}


func (b *FunctionDefinitionBuilder) RenderExpr() ast.Expr {
	return b.fun
}