package generate

import (
	"go/ast"
)

// this file is autogenerated.
// run `go generate` to update it.

// WithDoc attaches documentation to this Package.
func (b *PackageBuilder) WithDoc(lines ...string) *PackageBuilder {
	if len(lines) > 0 {
		b.file.Doc = createDocComment(lines)
	}
	return b
}


func (b *PackageBuilder) RenderFile() *ast.File {
	return b.file
}