package generate

import (
	"go/ast"
)

// this file is autogenerated.
// run `go generate` to update it.

func (b *BlockBuilder) RenderBlockStmt() *ast.BlockStmt {
	return b.block
}


func (b *BlockBuilder) RenderStmt() ast.Stmt {
	return b.block
}


func (b *AssignBuilder) RenderStmt() ast.Stmt {
	return b.stmt
}


func (b *IfStatementBuilder) RenderStmt() ast.Stmt {
	return b.stmt
}


func (b *CaseClauseBuilder) RenderCaseClause() *ast.CaseClause {
	return b.cl
}


func (b *SwitchStatementBuilder) RenderStmt() ast.Stmt {
	return b.stmt
}


func (b *TypeSwitchStatementBuilder) RenderStmt() ast.Stmt {
	return b.stmt
}


func (b *SelectClauseBuilder) RenderCommClause() *ast.CommClause {
	return b.cl
}


func (b *SelectStatementBuilder) RenderStmt() ast.Stmt {
	return b.stmt
}